config/routes.rb
Rails.application.routes.draw do
  # dashboard routes
  root 'home#home'
  post '/', to: 'home#create_tweet'
  get 'tweet/:id', to: 'tweets#show_tweet'
  resources :tweet, only: [:destroy], to: 'tweets#destroy'

  # comments
  post 'tweet/:id', to: 'tweets#create_comment'

  # likes
  post 'like/:id', to: 'tweets#create_like'
  resources :likes, only: [:destroy], to: 'tweets#unlike_tweet'

  # for you page
  get 'for-you', to: 'home#for_you_tweets'
  post 'for-you', to: 'home#create_tweet'

  # follow and unfollow users
  post '/follow/:id', to: 'user#follow_user'
  resources :friendship, only: [:destroy], to: 'user#unfollow_user'

  # login routes
  get 'login', to: 'user#new_session'
  post 'login', to: 'user#create_session'
  delete 'logout', to: 'user#destroy'

  # signup routes
  get 'signup', to: "user#new_user"
  post 'signup', to: 'user#create_user'

  # user profiles
  get 'user_profile/:id', to: 'user#show_user'
  get 'user/:id', to: 'user#edit_user'
  post 'user/:id', to: 'user#update_user'
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  after_initialize :set_default

  def set_default
    likes = 0
  end

  belongs_to :user
  has_many :comments
  has_many :likes

  validates :message, presence: true, length: {minimum: 1, maximum: 280}

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def new_comment
    user_info()
    @comment = Comment.new
  end

  def create_comment
    @user = session[:user_id]
    @comment = Comment.new(params.permit(:message))
    @comment.user_id = @user
    @comment.tweet_id = params[:id]
    if @comment.save
      # flash[:notice] = "Tweet successful"
      redirect_to tweet_path
    else
      flash.now[:notice] = "Something went wrong"
    end
  end

  def show_tweet
    if !session[:user_id]
      # redirect_to login_path
      render 'components/not_logged_in_page'
    else
      user_info()
      @comments = @tweet.comments.reverse
    end
  end

  def destroy
    # find tweet by id
    # delete tweet
    user_info()
    @tweet.destroy
    redirect_to root_path
  end

  #Likes
  def create_like
    user_info()
    @like = Like.new(user_id: @user.id, tweet_id: @tweet.id)
    done_with_like()
  end

  def unlike_tweet
    user_info()
    @like = Like.find_by(user_id: @user.id, tweet_id: @tweet.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end

  private
  def user_info
    @user = User.find(session[:user_id])
    @tweet = Tweet.find(params[:id])
    @following = @user.friends.count
    @followers = Friendship.where(friend_id: @user.id).count
  end

  def done_with_like
    if @like.save
      # flash[:notice] = "Tweet liked"
      redirect_back(fallback_location: root_path)
    else
      flash[:notice] = "something went wrong"
    end
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_comments.html.erb
<% if @comments.count < 1 %>
    <p>No comments.</p>
<%else%>
    <%@comments.each do |comment|%>
        <div class="container border p-2 comment-width" >
            <div class="d-inline-flex rounded p-2" onclick="location.href='/user_profile/<%=comment.user_id%>';">
                <p style="margin-right: 5px;"><%=comment.user.name%></p>
                <p style="color: gray; cursor: pointer;">@<%=comment.user.username%></p>
            </div>
                <div class="container" >
                    <h6 class="" style="font-family: Tahoma, sans-serif;"><%=comment.message%></h6>
                </div>
                <div class="container d-flex justify-content-between align-items-center">
                    <div>
                        <small style="color: gray;"><%=time_ago_in_words(comment.created_at)%></small>
                    </div>
                </div>
        </div>
    <%end%>
<%end%>

app/views/tweets/_new_tweet.html.erb
<div class="mb-3 mt-3 tweet-width">
    <%=form_with(model: @tweet, local: true) do |f|%>
        <%=f.text_area :message, class: "form-control div-h", placeholder: "What's on your mind?"%>
        <div class="position-relative">
            <button type="submit" class="btn btn-primary position-absolute bottom-0 end-0 m-3">Tweet</button>
        </div>
        <div class="position-relative">
            <p class="btn text-white position-absolute bottom-0 start-0 m-3" id="img-btn"><i class="fa-regular fa-image"></i></p>
        </div>
        <%=f.text_field :image, class: "form-control mt-2 hide-box", id: "image-container", placeholder: "Image Link"%>
    <%end%>
</div>

<script>
    $(() => {
        $img = $('#image-container');
        $imgButton = $("#img-btn");
        $imgButton.on('click', function(){
            $img.toggleClass('hide-box')
        })
    });
</script>

app/views/tweets/_tweets.html.erb
<% if @tweets.count < 1 %>
    <p>Follow to see tweets.</p>
<%else%>
    <%@tweets.each do |tweet|%>
        <div class="container border p-2 tweet-width" id="<%=tweet.id%>">
        <%# tweet creator info %>
            <div class="d-inline-flex rounded p-2" onclick="location.href='/user_profile/<%=tweet.user.id%>';">
                <p style="margin-right: 5px;"><%=tweet.user.name%></p>
                <p style="color: gray; cursor: pointer;">@<%=tweet.user.username%></p>
            </div>
            <%# tweet message %>
            <div class="" style="cursor: pointer;" onclick="location.href='/tweet/<%=tweet.id%>';">
                <div class="container" >
                    <h6 style="font-family: Tahoma, sans-serif;"><%=tweet.message%></h6>
                </div>
            <%# tweet image %>
            <%if tweet.image?%>
                <div class="container d-flex align-items-center justify-content-center">
                    <img class="tweet_img border mt-2 " src="<%=tweet.image%>" alt="image from @<%=tweet.user.username%>>">
                </div>
            <%end%>

            </div>
            <%# like and comments buttons %>
            <div class="container d-flex align-items-center justify-content-end" >
                <%# time tweeted %>
                <div class="container">
                    <small style="color: gray;"><%=time_ago_in_words(tweet.created_at)%> ago</small>
                </div>
                <%# like button %>
                <%if @user.liked_tweet?(tweet.id)%>
                    <%= link_to '<i class="fa-solid fa-heart"></i>'.html_safe, like_path(tweet), data: {turbo_method: :delete}, class: "btn"%>
                <%else%>
                    <form action="/like/<%=tweet.id%>" method="post">
                        <button type="submit" class="btn"><i class="fa-regular fa-heart"></i></button>
                    </form>
                <%end%>
                <%# Like count %>
                <span><%= tweet.likes.count%></span>
                <%# comment count %>
                <div>
                    <div class="d-flex align-items-center justify-content-end" onclick="location.href='/tweet/<%=tweet.id%>';">
                        <button class="btn"><i class="fa-regular fa-comment"></i></button>
                        <span><%= tweet.comments.count%></span>
                    </div>
                </div>
            </div>
            <%# end of likes and comments %>
        </div>
    <%end%>
<%end%>

app/views/tweets/_tweets_no_stats.html.erb
<% if @tweets.count < 1 %>
    <p>No Tweets to see.</p>
<%else%>
    <%@tweets.each do |tweet|%>
        <div class="container border p-2 tweet-width">
        <%# tweet creator info %>
            <div class="d-inline-flex rounded p-2" onclick="location.href='/user_profile/<%=tweet.user.id%>';">
                <p style="margin-right: 5px;"><%=tweet.user.name%></p>
                <p style="color: gray; cursor: pointer;">@<%=tweet.user.username%></p>
            </div>
            <%# tweet message %>
            <div style="cursor: pointer;" onclick="location.href='/tweet/<%=tweet.id%>';">
                <div class="container" >
                    <h6 style="font-family: Tahoma, sans-serif;"><%=tweet.message%></h6>
                </div>
            <%# tweet image %>
            <%if tweet.image?%>
                <div class="container d-flex align-items-center justify-content-center">
                    <img class="tweet_img border mt-2 " src="<%=tweet.image%>" alt="image from @<%=tweet.user.username%>>">
                </div>
            <%end%>

            </div>
            <%# like and comments buttons %>
            <div class="container d-flex align-items-center justify-content-end" >
                <%# time tweeted %>
                <div class="container">
                    <small style="color: gray;"><%=time_ago_in_words(tweet.created_at)%> ago</small>
                </div>
                <%# Like count %>
                <i class="fa-solid fa-heart me-2"></i>
                <span><%= tweet.likes.count%></span>
                <%# comment count %>
                <div>
                    <div class="d-flex align-items-center justify-content-end" onclick="location.href='/tweet/<%=tweet.id%>';">
                        <button class="btn"><i class="fa-regular fa-comment"></i></button>
                        <span><%= tweet.comments.count%></span>
                    </div>
                </div>
            </div>
            <%# end of likes and comments %>
        </div>
    <%end%>
<%end%>

app/views/tweets/show_tweet.html.erb
<div class="container d-flex logo-mobile">
    <%=render 'components/back_button'%>
</div>
<div class="container d-flex">
    <%=render 'components/side_bar'%>
</div>
<div class="container p-2 d-flex flex-column justify-content-center align-items-center mt-3">
    <%# tweet creater info %>
    <div class="border rounded p-3 tweet-width ">
        <div class="d-inline-flex align-items-center" style="cursor: pointer;" onclick="location.href='/user_profile/<%=@tweet.user.id%>';">
            <p style="margin-right: 5px;"><%=@tweet.user.name%></p>
            <p style="color: gray; margin-right: 5px;">@<%=@tweet.user.username%></p>
            <p style="color: gray; font-size: smaller;">• <%=time_ago_in_words(@tweet.created_at)%></p>
        </div>
        <%# message %>
        <div class="container">
            <p class="fs-4"><%=@tweet.message%></p>
        </div>
        <%# image %>
        <%if @tweet.image?%>
            <div class="container d-flex align-items-center justify-content-center">
                <img class="tweet_img mb-3 border" src="<%=@tweet.image%>" alt="">
            </div>
        <%end%>

        <%# like and comment container %>
        <div class="container d-flex align-items-center justify-content-end" >
            <%if @user.liked_tweet?(@tweet.id)%>
                <%= link_to '<i class="fa-solid fa-heart"></i>'.html_safe, like_path(@tweet), data: {turbo_method: :delete}, class: "btn"%>
            <%else%>
                <form action="/like/<%=@tweet.id%>" method="post">
                    <button type="submit" class="btn"><i class="fa-regular fa-heart"></i></button>
                </form>
            <%end%>
            <span><%= @tweet.likes.count%></span>
            <div>
                <div class="d-flex align-items-center justify-content-end" onclick="location.href='/tweet/<%=@tweet.id%>';">
                    <button class="btn"><i class="fa-regular fa-comment"></i></button>
                    <span><%= @tweet.comments.count%></span>
                </div>
            </div>
        </div>
        <%# delete tweet %>
        <%if @tweet.user_id == session[:user_id]%>
        <div class="position-relative mt-5">
            <%= link_to 'Delete', tweet_path(@tweet), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger position-absolute bottom-0 end-0"%>
        </div>
        <%end%>
    </div>
    <%# comments %>
    <div class="mb-3 mt-3 tweet-width">
        <p>Comments</p>
        <%# new comment form %>
        <%=form_with(model: @comment, local: true) do |f|%>
            <%=f.text_area :message, class: "form-control div-c", placeholder: "Add comment"%>
            <div class="position-relative">
                <button type="submit" class="btn btn-primary position-absolute bottom-0 end-0 m-3">Comment</button>
            </div>
        <%end%>
    </div>
    <%# comments section %>
    <%= render 'tweets/comments'%>
</div>