config/routes.rb
Rails.application.routes.draw do
  # dashboard routes
  root 'home#home'
  post '/', to: 'home#create_tweet'
  get 'tweet/:id', to: 'tweets#show_tweet'
  resources :tweet, only: [:destroy], to: 'tweets#destroy'

  # comments
  post 'tweet/:id', to: 'tweets#create_comment'

  # likes
  post 'like/:id', to: 'tweets#create_like'
  resources :likes, only: [:destroy], to: 'tweets#unlike_tweet'

  # for you page
  get 'for-you', to: 'home#for_you_tweets'
  post 'for-you', to: 'home#create_tweet'

  # follow and unfollow users
  post '/follow/:id', to: 'user#follow_user'
  resources :friendship, only: [:destroy], to: 'user#unfollow_user'

  # login routes
  get 'login', to: 'user#new_session'
  post 'login', to: 'user#create_session'
  delete 'logout', to: 'user#destroy'

  # signup routes
  get 'signup', to: "user#new_user"
  post 'signup', to: 'user#create_user'

  # user profiles
  get 'user_profile/:id', to: 'user#show_user'
  get 'user/:id', to: 'user#edit_user'
  post 'user/:id', to: 'user#update_user'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
    if !session[:user_id]
      # redirect_to login_path
      render 'components/not_logged_in_page'
    else
      # show tweets from the user they are following
      user_info()
      @tweets = Tweet.where(user_id: @user.friends.all).or(Tweet.where(user_id: @user.id)).reverse
    end
  end

  def for_you_tweets
    if !session[:user_id]
      # redirect_to login_path
      render 'components/not_logged_in_page'
    else
       # show tweets from the user that the current user isnt following
      user_info
      @tweets = Tweet.where.not(user_id: @user.friends.all).and(Tweet.where.not(user_id: @user.id)).reverse
    end
  end

  def new_tweet
    @tweet = Tweet.new
  end

  def create_tweet
    @tweet = Tweet.new(params.permit(:message, :image))
    @tweet.user_id = session[:user_id]
    if @tweet.save
      # flash[:notice] = "Tweet successful"
      redirect_back(fallback_location: root_path)
    else
      flash.now[:notice] = "Something went wrong"
    end
  end

  private
  def user_info
    @user = User.find(session[:user_id])
    @following = @user.friends.count
    @followers = Friendship.where(friend_id: @user.id).count
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_side_bar.html.erb
<div class="side-bar ">
    <h1>Tweetter</h1>
    <div class="border rounded p-3 text-center">
        <p>Welcome, <strong><%= @user.name%></strong></p>
        <p>@<strong><%= @user.username%></strong></p>
        <p>Followers: <%= @followers%></p>
        <p>Following: <%= @following%></p>
    </div>
    <%= link_to 'Logout', login_path, data: { turbo_method: :delete }, data: {confirm: "Are you sure?"}, class: "btn btn-light my-3" %>
</div>

app/views/home/for_you_tweets.html.erb
<div class="container d-flex">
    <%=render 'components/side_bar'%>
    <%# feed filter %>
    <div class="container p-2 d-inline-flex flex-column justify-content-center align-items-center mt-3 ms-3">
        <div class="mb-2 border text-bg-dark d-inline-flex justify-content-center align-items-end sticky-top p-2 tweet-width">
            <ul class="nav nav-underline">
                <li class="nav-item me-5" id="for_you">
                    <a class="nav-link active" href="/for-you">For You</a>
                </li>
                <li class="nav-item ms-5" id="following">
                    <a class="nav-link" aria-current="page" href="/">Following</a>
                </li>
            </ul>
        </div>
        <%# tweet message partial %>
        <%=render 'tweets/new_tweet'%>
        <%# tweet container %>
        <%=render 'tweets/tweets'%>
        <%=render 'components/logo'%>
    </div>
</div>

app/views/home/home.html.erb
<div class="container d-flex">

    <%=render 'components/side_bar'%>
    <%# feed filter %>
    <div class="container p-2 d-inline-flex flex-column justify-content-center align-items-center mt-3 ms-3 p-auto">
        <div class="mb-2 border text-bg-dark d-inline-flex justify-content-center align-items-end sticky-top p-2 tweet-width">
            <ul class="nav nav-underline">
                <li class="nav-item me-5" id="for_you">
                    <a class="nav-link" href="/for-you">For You</a>
                </li>
                <li class="nav-item ms-5" id="following">
                    <a class="nav-link active" aria-current="page" href="/">Following</a>
                </li>
            </ul>
        </div>
        <%# tweet message partial %>
        <%=render 'tweets/new_tweet'%>
        <%# tweet container %>
        <%=render 'tweets/tweets'%>

        <%=render 'components/logo'%>
    </div>
</div>

app/views/home/show_tweet.html.erb
<div class="container p-2 d-flex flex-column justify-content-center align-items-center">
    <a onclick="history.go(-1)" class="container">
        <button class="btn btn-primary">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
            </svg>
            Back
        </button>
    </a>
    <div class="container border rounded p-2" style="width: 55%;">
        <div class="d-inline-flex" style="cursor: pointer;" onclick="location.href='/user/<%=@tweet.user.id%>';">
            <p style="margin-right: 5px;"><%=@tweet.user.name%></p>
            <p style="color: gray;">@<%=@tweet.user.username%></p>
        </div>
        <div class="container">
            <p class="fs-4"><%=@tweet.message%></p>
            <small style="color: gray;"><%=time_ago_in_words(@tweet.created_at)%></small>
        </div>
        <%if @tweet.user_id == session[:user_id]%>
        <div class="position-relative">
            <%= link_to 'Delete', tweet_path(@tweet), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger position-absolute bottom-0 end-0"%>
        </div>
        <%end%>
    </div>
</div>