config/routes.rb
Rails.application.routes.draw do
  # dashboard routes
  root 'home#home'
  post '/', to: 'home#create_tweet'
  get 'tweet/:id', to: 'tweets#show_tweet'
  resources :tweet, only: [:destroy], to: 'tweets#destroy'

  # comments
  post 'tweet/:id', to: 'tweets#create_comment'

  # likes
  post 'like/:id', to: 'tweets#create_like'
  resources :likes, only: [:destroy], to: 'tweets#unlike_tweet'

  # for you page
  get 'for-you', to: 'home#for_you_tweets'
  post 'for-you', to: 'home#create_tweet'

  # follow and unfollow users
  post '/follow/:id', to: 'user#follow_user'
  resources :friendship, only: [:destroy], to: 'user#unfollow_user'

  # login routes
  get 'login', to: 'user#new_session'
  post 'login', to: 'user#create_session'
  delete 'logout', to: 'user#destroy'

  # signup routes
  get 'signup', to: "user#new_user"
  post 'signup', to: 'user#create_user'

  # user profiles
  get 'user_profile/:id', to: 'user#show_user'
  get 'user/:id', to: 'user#edit_user'
  post 'user/:id', to: 'user#update_user'
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}

  validates :name, presence: true, length: {minimum: 1, maximum: 50}

  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:true, uniqueness: {case_sensitive: false}, length: { maximum: 105}, format: {with: VALID_EMAIL_REGEX}

  has_secure_password

  has_many :tweets
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :comments
  has_many :likes


  def not_friends_with?(id)
    !self.friends.where(id: id).exists?
  end

  def liked_tweet?(tweet_id)
    self.likes.where(tweet_id: tweet_id).exists?
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  # signup
  def new_user
    @user = User.new
  end

  def create_user
    # create new user with params
    @user = User.new(params.require(:user).permit(:name, :username, :email, :password))
    # if user is valid then it saves
    if @user.save
      # flash[:notice] = "Account Successfully created"
      # redirect to login page
      redirect_to '/login'
    else
      # error - re-render page
      render 'new_user', status: :unprocessable_entity
    end
  end

  # login/session
  def new_session

  end

  def create_session
    # find user by username
    @user = User.find_by(username: params[:user][:username])
    # check password
    if @user && @user.authenticate(params[:user][:password])
      # set session to logged in user
      session[:user_id] = @user.id
      # display success notice
      # flash[:notice] = "Successful login"
      # go back to home/dashboard
      redirect_to root_path
    else
      flash.now[:alert] = "Incorrect username or password. Try again"
      render 'new_session', status: :unprocessable_entity
    end
  end

  def end_session
    # set session to nil
    session[:user_id] = nil
    flash[:notice] = "Logged Out"
    # redirect back to login page
    redirect_to '/login'
  end

  # user profile
  def show_user
    if !session[:user_id]
      # redirect_to login_path
      render 'components/not_logged_in_page'
    else
      @user = User.find(params[:id])
      @current_user = User.find(session[:user_id])
      @tweets = Tweet.where(user_id: @user.id).reverse
      @following = @user.friends.count
      @followers = Friendship.where(friend_id: @user.id).count
    end
  end

  def edit_user
    @user = User.find(session[:user_id])
  end

  def update_user
    @user = User.find(session[:user_id])
    if @user.update(params.require(:user).permit(:name, :username))
      redirect_to root_path
    else
      flash.now[:notice] = 'Something went wrong'
      render 'edit_user'
    end
  end



  def follow_user
    # friend = User.find(params[:id])
    current_user = User.find(session[:user_id])
    current_user.friendships.build(friend_id: params[:id])
    if current_user.save
      # flash[:notice] = 'Now Following'
      redirect_back(fallback_location: root_path)
    else
      flash[:notice] = 'Something went wrong'
      redirect_to root_path
    end
  end

  def unfollow_user
    # find current user
    current_user = User.find(session[:user_id])
    # grab the friendship between current and user based on show page
    friendship = current_user.friendships.where(friend_id: params[:id]).first
    # 'unfollow' user
    friendship.destroy
    # flash[:notice] = "Stopped unfollowed"
    redirect_back(fallback_location: root_path)
  end

end

app/views/user/edit_user.html.erb
<div class="container d-flex flex-column justify-content-center align-items-center border rounded mt-5 p-2">

<% if @user.errors.any? %>
        <h2>The following errors prevented the user from being saved: </h2>
        <ul>
            <%@user.errors.full_messages.each do |msg|%>
                <li><%=msg%></li>
            <%end%>
        </ul>
    <%end%>
    <div>
        <h1>Update Profile</h1>
    </div>
    <div class="p-3">
    <%= form_with(scope: :user, local: true) do |f|%>
        <p>
            <%=f.label :name%>
            <br>
            <%=f.text_field :name%>
        </p>
        <p>
            <%=f.label :username%>
            <br>
            <%=f.text_field :username%>
        </p>
        <button type="submit" class="btn btn-primary">Make changes</button>
        <a href="/">Cancel</a>

    <%end%>
    <br>
    <div class="text-danger">
        <%flash.each do |name, msg|%>
            <%=msg%>
        <%end%>
    </div>
</div>

app/views/user/new_session.html.erb
<div class="container d-flex flex-column justify-content-center align-items-center border rounded mt-5 p-2">
    <div>
        <h1>Login</h1>
    </div>
    <div class="p-3">
    <%= form_with(scope: :user, url: login_path, local: true) do |f|%>
        <p>
            <%=f.label :username%>
            <br>
            <%=f.text_field :username%>
        </p>
        <p>
            <%=f.label :password%>
            <br>
            <%=f.password_field :password%>
        </p>
        <button type="submit" class="btn btn-primary">Log In</button>

    <%end%>
    <br>
    <span class="text-white text-decoration-none">New user?</span>
    <a href="/signup">Sign up.</a>
    </div>
    <div class="text-danger">
        <%flash.each do |name, msg|%>
            <%=msg%>
        <%end%>
    </div>
</div>

app/views/user/new_user.html.erb
<div class="container d-flex flex-column justify-content-center align-items-center border rounded mt-5">
    <div class="">

    <h1>Signup</h1>

    <% if @user.errors.any? %>
        <h2>The following errors prevented the user from being saved: </h2>
        <ul>
            <%@user.errors.full_messages.each do |msg|%>
                <li><%=msg%></li>
            <%end%>
        </ul>
    <%end%>
    </div>

    <div class="p-3">
    <%= form_with(scope: :user, local: true) do |f|%>
        <p>
            <%=f.label :name%>
            <br>
            <%=f.text_field :name%>
        </p>

        <p>
            <%=f.label :username%>
            <br>
            <%=f.text_field :username%>
        </p>

        <p>
            <%=f.label :email%>
            <br>
            <%=f.text_field :email%>
        </p>

        <p>
            <%=f.label :password%>
            <br>
            <%=f.password_field :password%>
        </p>
        <button type="submit" class="btn btn-light">Signup</button>
    <%end%>
    <br>
    <a href="/login">
        Already a user? Log In.
    </a>
    </div>
</div>

app/views/user/show_user.html.erb
<div class="container mb-2">
    <div class=" mt-5">
        <%=render 'components/back_button'%>
    </div>
    <div class="d-flex flex-column justify-content-center align-items-center mb-4">
        <div class="d-flex justify-content-center align-items-center">
            <h1>@<%=@user.username%></h1>
            <%if @current_user.id === @user.id%>
                <a href="/user/<%=@user.id%>" class="text-white ms-2">
                    <i class="fa-regular fa-pen-to-square fa-lg"></i>
                </a>
            <%end%>
        </div>
        <div class="d-flex" style="color: gray;">
            <p class="me-3">Following: <%=@following%></p>
            <p>Followers: <%=@followers%></p>
        </div>
        <div>
            <%if @current_user.id != @user.id%>
                <%if @current_user.id != @user.id && @current_user.not_friends_with?(@user.id)%>
                    <form action="/follow/<%=@user.id%>" method="post">
                        <button type="submit" class="btn btn-primary">Follow</button>
                    </form>
                <% else %>
                    <%= link_to 'Unfollow', friendship_path(@user), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-danger"%>
                <%end%>
            <%end%>
        </div>
    <br>
    <%=render 'tweets/tweets_no_stats'%>
    </div>
</div>